services:
  database:
      image: postgres:16
      container_name: hackyeah-dev-database
      ports:
        - "5432:5432"
      restart: unless-stopped
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=hackyeah
      volumes:
        - dev_database:/var/lib/postgresql/data

volumes:
  dev_database: