services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: hackyeah-dev-elasticsearch
    network_mode: host
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    mem_limit: 2g

  database:
      image: postgres:16
      container_name: hackyeah-dev-database
      ports:
        - "5432:5432"
      restart: unless-stopped
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=hackyeah
      volumes:
        - dev_database:/var/lib/postgresql/data

volumes:
  dev_database: