import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from '@/auth';
<<<<<<< HEAD
=======
import Script from "next/script";
>>>>>>> 0affe00c40e6b766c84487ef5941e04145a7d9f3

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          {children}
<<<<<<< HEAD
=======
          <Script
            src="https://cdn.cubing.net/js/scramble-display"
            type="module"
          />
>>>>>>> 0affe00c40e6b766c84487ef5941e04145a7d9f3
        </body>
      </html>
    </SessionProvider>
  );
}
